// Menu categories data
export const menuCategories = [
  {
    name: "Digital Deals & Exclusives",
    icon: "🍔",
    href: "/deals",
  },
  {
    name: "Game Day Munchies",
    icon: "🌮",
    href: "/game-day",
  },
  {
    name: "Jack's Munchies Under $4",
    icon: "🥪",
    href: "/munchies",
  },
  {
    name: "Burger Combos",
    icon: "🍔",
    href: "/burger-combos",
  },
  {
    name: "Chicken Combos",
    icon: "🍗",
    href: "/chicken-combos",
  },
  {
    name: "Breakfast Combos",
    icon: "🥞",
    href: "/breakfast-combos",
  },
  {
    name: "Late Night",
    icon: "🌙",
    href: "/late-night",
  },
  {
    name: "Tacos",
    icon: "🌮",
    href: "/tacos",
  },
  {
    name: "Fries & Sides",
    icon: "🍟",
    href: "/sides",
  },
  {
    name: "Shakes & Desserts",
    icon: "🥤",
    href: "/desserts",
  },
  {
    name: "Drinks",
    icon: "🥤",
    href: "/drinks",
  },
  {
    name: "Burgers",
    icon: "🍔",
    href: "/burgers",
  },
  {
    name: "Chicken",
    icon: "🍗",
    href: "/chicken",
  },
  {
    name: "All Day Breakfast",
    icon: "🍳",
    href: "/breakfast",
  },
  {
    name: "Lighter Options",
    icon: "🥗",
    href: "/lighter",
  },
  {
    name: "Kids",
    icon: "🧒",
    href: "/kids",
  },
]

// Menu items data with detailed information
export const menuItems = [
  // Burgers
  {
    id: "burger-1",
    category: "burgers",
    name: "Classic Cheeseburger",
    emoji: "🍔",
    price: 4.99,
    description:
      "A juicy beef patty topped with American cheese, lettuce, tomato, pickles, and our special sauce on a toasted bun.",
    tags: ["Beef", "Cheese", "Classic"],
    nutrition: {
      calories: 650,
      protein: 28,
      carbs: 45,
      fat: 38,
    },
  },
  {
    id: "burger-2",
    category: "burgers",
    name: "Bacon Ultimate Cheeseburger",
    emoji: "🍔",
    price: 6.99,
    description: "Two beef patties, three slices of American cheese, and four strips of bacon on a buttery bakery bun.",
    tags: ["Beef", "Bacon", "Cheese"],
    nutrition: {
      calories: 930,
      protein: 52,
      carbs: 48,
      fat: 62,
    },
  },
  {
    id: "burger-3",
    category: "burgers",
    name: "Sourdough Jack",
    emoji: "🍔",
    price: 5.99,
    description: "Beef patty with Swiss-style cheese, bacon, tomato, and mayo on grilled sourdough bread.",
    tags: ["Beef", "Bacon", "Sourdough"],
    nutrition: {
      calories: 710,
      protein: 34,
      carbs: 42,
      fat: 46,
    },
  },
  {
    id: "burger-4",
    category: "burgers",
    name: "Jumbo Jack",
    emoji: "🍔",
    price: 3.99,
    description:
      "100% beef patty topped with lettuce, tomato, pickles, chopped onions, and mayo on a buttery bakery bun.",
    tags: ["Beef", "Classic", "Value"],
    nutrition: {
      calories: 510,
      protein: 23,
      carbs: 46,
      fat: 28,
    },
  },

  // Chicken
  {
    id: "chicken-1",
    category: "chicken",
    name: "Crispy Chicken Sandwich",
    emoji: "🍗",
    price: 5.49,
    description: "Crispy chicken fillet topped with lettuce, tomato, and mayo on a toasted bun.",
    tags: ["Crispy", "Chicken", "Sandwich"],
    nutrition: {
      calories: 490,
      protein: 24,
      carbs: 52,
      fat: 22,
    },
  },
  {
    id: "chicken-2",
    category: "chicken",
    name: "Spicy Chicken Sandwich",
    emoji: "🔥",
    price: 5.99,
    description: "Spicy crispy chicken fillet with lettuce, tomato, and spicy sauce on a toasted bun.",
    tags: ["Spicy", "Chicken", "Sandwich"],
    nutrition: {
      calories: 510,
      protein: 25,
      carbs: 53,
      fat: 24,
    },
  },
  {
    id: "chicken-3",
    category: "chicken",
    name: "Chicken Strips (4pc)",
    emoji: "🍗",
    price: 4.99,
    description: "Four pieces of crispy, all-white-meat chicken strips with your choice of dipping sauce.",
    tags: ["Strips", "Crispy", "Dipping Sauce"],
    nutrition: {
      calories: 570,
      protein: 32,
      carbs: 38,
      fat: 32,
    },
  },

  // Chicken Combos
  {
    id: "chicken-combo-1",
    category: "chicken-combos",
    name: "Crispy Chicken Combo",
    emoji: "🍗",
    price: 8.49,
    description: "Crispy chicken sandwich with small fries and a small drink.",
    tags: ["Combo", "Chicken", "Fries", "Drink"],
    nutrition: {
      calories: 890,
      protein: 28,
      carbs: 112,
      fat: 38,
    },
  },
  {
    id: "chicken-combo-2",
    category: "chicken-combos",
    name: "Spicy Chicken Combo",
    emoji: "🔥",
    price: 8.99,
    description: "Spicy chicken sandwich with small fries and a small drink.",
    tags: ["Combo", "Spicy", "Fries", "Drink"],
    nutrition: {
      calories: 910,
      protein: 29,
      carbs: 113,
      fat: 40,
    },
  },
  {
    id: "chicken-combo-3",
    category: "chicken-combos",
    name: "Chicken Strips Combo",
    emoji: "🍗",
    price: 7.99,
    description: "Four crispy chicken strips with small fries, a small drink, and your choice of dipping sauce.",
    tags: ["Combo", "Strips", "Fries", "Drink"],
    nutrition: {
      calories: 970,
      protein: 36,
      carbs: 98,
      fat: 48,
    },
  },

  // Breakfast
  {
    id: "breakfast-1",
    category: "breakfast",
    name: "Sausage Breakfast Jack",
    emoji: "🍳",
    price: 3.49,
    description: "Freshly fried egg, sausage patty, and American cheese on a bun.",
    tags: ["Breakfast", "Sausage", "Egg"],
    nutrition: {
      calories: 420,
      protein: 19,
      carbs: 30,
      fat: 26,
    },
  },
  {
    id: "breakfast-2",
    category: "breakfast",
    name: "Bacon Breakfast Jack",
    emoji: "🥓",
    price: 3.29,
    description: "Freshly fried egg, bacon, and American cheese on a bun.",
    tags: ["Breakfast", "Bacon", "Egg"],
    nutrition: {
      calories: 350,
      protein: 17,
      carbs: 30,
      fat: 20,
    },
  },
  {
    id: "breakfast-3",
    category: "breakfast",
    name: "Supreme Croissant",
    emoji: "🥐",
    price: 4.49,
    description: "Flaky croissant with grilled bacon, ham, freshly fried egg, and American cheese.",
    tags: ["Breakfast", "Croissant", "Bacon", "Ham"],
    nutrition: {
      calories: 510,
      protein: 23,
      carbs: 32,
      fat: 34,
    },
  },
  {
    id: "breakfast-4",
    category: "breakfast",
    name: "Loaded Breakfast Sandwich",
    emoji: "🥪",
    price: 4.99,
    description: "Grilled sourdough bread with bacon, ham, sausage, freshly fried egg, and American cheese.",
    tags: ["Breakfast", "Sourdough", "Loaded"],
    nutrition: {
      calories: 710,
      protein: 36,
      carbs: 38,
      fat: 48,
    },
  },

  // Breakfast Combos
  {
    id: "breakfast-combo-1",
    category: "breakfast-combos",
    name: "Sausage Breakfast Jack Combo",
    emoji: "🍳",
    price: 5.99,
    description: "Sausage Breakfast Jack with hash browns and a small coffee.",
    tags: ["Combo", "Breakfast", "Sausage", "Coffee"],
    nutrition: {
      calories: 620,
      protein: 21,
      carbs: 58,
      fat: 36,
    },
  },
  {
    id: "breakfast-combo-2",
    category: "breakfast-combos",
    name: "Supreme Croissant Combo",
    emoji: "🥐",
    price: 6.99,
    description: "Supreme Croissant with hash browns and a small coffee.",
    tags: ["Combo", "Breakfast", "Croissant", "Coffee"],
    nutrition: {
      calories: 710,
      protein: 25,
      carbs: 60,
      fat: 44,
    },
  },
  {
    id: "breakfast-combo-3",
    category: "breakfast-combos",
    name: "Loaded Breakfast Sandwich Combo",
    emoji: "🥪",
    price: 7.49,
    description: "Loaded Breakfast Sandwich with hash browns and a small coffee.",
    tags: ["Combo", "Breakfast", "Loaded", "Coffee"],
    nutrition: {
      calories: 910,
      protein: 38,
      carbs: 66,
      fat: 58,
    },
  },

  // Tacos
  {
    id: "taco-1",
    category: "tacos",
    name: "2 Tacos",
    emoji: "🌮",
    price: 1.99,
    description: "Two crunchy tacos with American cheese, shredded lettuce, and taco sauce.",
    tags: ["Tacos", "Value", "Classic"],
    nutrition: {
      calories: 340,
      protein: 12,
      carbs: 30,
      fat: 18,
    },
  },
  {
    id: "taco-2",
    category: "tacos",
    name: "Loaded Tiny Tacos",
    emoji: "🌮",
    price: 4.99,
    description: "15 tiny tacos topped with cheese sauce, shredded lettuce, and taco sauce.",
    tags: ["Tacos", "Loaded", "Cheese"],
    nutrition: {
      calories: 470,
      protein: 15,
      carbs: 42,
      fat: 28,
    },
  },
  {
    id: "taco-3",
    category: "tacos",
    name: "Tiny Tacos (15pc)",
    emoji: "🌮",
    price: 3.99,
    description: "15 crunchy, bite-sized tacos with dipping sauce.",
    tags: ["Tacos", "Tiny", "Dipping Sauce"],
    nutrition: {
      calories: 390,
      protein: 13,
      carbs: 36,
      fat: 24,
    },
  },

  // Fries & Sides
  {
    id: "side-1",
    category: "sides",
    name: "French Fries (Small)",
    emoji: "🍟",
    price: 2.29,
    description: "Crispy, golden french fries seasoned with salt.",
    tags: ["Fries", "Side", "Classic"],
    nutrition: {
      calories: 320,
      protein: 4,
      carbs: 42,
      fat: 15,
    },
  },
  {
    id: "side-2",
    category: "sides",
    name: "Curly Fries (Small)",
    emoji: "🍟",
    price: 2.79,
    description: "Seasoned, curly-cut fried potatoes.",
    tags: ["Fries", "Curly", "Seasoned"],
    nutrition: {
      calories: 350,
      protein: 5,
      carbs: 44,
      fat: 18,
    },
  },
  {
    id: "side-3",
    category: "sides",
    name: "Onion Rings",
    emoji: "⭕",
    price: 2.99,
    description: "Crispy, battered onion rings.",
    tags: ["Onion", "Rings", "Crispy"],
    nutrition: {
      calories: 380,
      protein: 6,
      carbs: 46,
      fat: 20,
    },
  },
  {
    id: "side-4",
    category: "sides",
    name: "Stuffed Jalapeños (3pc)",
    emoji: "🌶️",
    price: 3.49,
    description: "Spicy jalapeños stuffed with cheese and deep-fried.",
    tags: ["Spicy", "Cheese", "Jalapeño"],
    nutrition: {
      calories: 240,
      protein: 7,
      carbs: 22,
      fat: 14,
    },
  },

  // Shakes & Desserts
  {
    id: "dessert-1",
    category: "desserts",
    name: "Oreo Shake",
    emoji: "🥤",
    price: 4.29,
    description: "Vanilla ice cream shake with Oreo cookie pieces.",
    tags: ["Shake", "Oreo", "Dessert"],
    nutrition: {
      calories: 710,
      protein: 12,
      carbs: 108,
      fat: 24,
    },
  },
  {
    id: "dessert-2",
    category: "desserts",
    name: "Chocolate Shake",
    emoji: "🍫",
    price: 3.99,
    description: "Rich chocolate ice cream shake.",
    tags: ["Shake", "Chocolate", "Dessert"],
    nutrition: {
      calories: 680,
      protein: 11,
      carbs: 102,
      fat: 23,
    },
  },
  {
    id: "dessert-3",
    category: "desserts",
    name: "Vanilla Shake",
    emoji: "🥛",
    price: 3.99,
    description: "Creamy vanilla ice cream shake.",
    tags: ["Shake", "Vanilla", "Dessert"],
    nutrition: {
      calories: 640,
      protein: 11,
      carbs: 98,
      fat: 22,
    },
  },
  {
    id: "dessert-4",
    category: "desserts",
    name: "Chocolate Overload Cake",
    emoji: "🍰",
    price: 3.49,
    description: "Rich chocolate cake with chocolate icing.",
    tags: ["Cake", "Chocolate", "Dessert"],
    nutrition: {
      calories: 420,
      protein: 5,
      carbs: 64,
      fat: 18,
    },
  },

  // Drinks
  {
    id: "drink-1",
    category: "drinks",
    name: "Soft Drink (Small)",
    emoji: "🥤",
    price: 1.99,
    description: "Your choice of fountain drink.",
    tags: ["Drink", "Soda", "Fountain"],
    nutrition: {
      calories: 150,
      protein: 0,
      carbs: 40,
      fat: 0,
    },
  },
  {
    id: "drink-2",
    category: "drinks",
    name: "Iced Tea (Small)",
    emoji: "🧊",
    price: 1.99,
    description: "Freshly brewed iced tea.",
    tags: ["Drink", "Tea", "Refreshing"],
    nutrition: {
      calories: 0,
      protein: 0,
      carbs: 0,
      fat: 0,
    },
  },
  {
    id: "drink-3",
    category: "drinks",
    name: "Coffee (Small)",
    emoji: "☕",
    price: 1.79,
    description: "Premium roast coffee.",
    tags: ["Drink", "Coffee", "Hot"],
    nutrition: {
      calories: 5,
      protein: 0,
      carbs: 0,
      fat: 0,
    },
  },
  {
    id: "drink-4",
    category: "drinks",
    name: "Orange Juice",
    emoji: "🍊",
    price: 2.49,
    description: "100% pure orange juice.",
    tags: ["Drink", "Juice", "Breakfast"],
    nutrition: {
      calories: 140,
      protein: 2,
      carbs: 33,
      fat: 0,
    },
  },

  // Deals
  {
    id: "deal-1",
    category: "deals",
    name: "4 for $4 Meal Deal",
    emoji: "💰",
    price: 4.0,
    description: "Your choice of sandwich with small fries, 4pc chicken nuggets, and a small drink.",
    tags: ["Deal", "Value", "Combo"],
    nutrition: {
      calories: 760,
      protein: 24,
      carbs: 92,
      fat: 36,
    },
  },
  {
    id: "deal-2",
    category: "deals",
    name: "2 for $6 Mix & Match",
    emoji: "🔄",
    price: 6.0,
    description: "Choose any two select menu items for just $6.",
    tags: ["Deal", "Mix", "Value"],
    nutrition: {
      calories: "Varies",
      protein: "Varies",
      carbs: "Varies",
      fat: "Varies",
    },
  },
  {
    id: "deal-3",
    category: "deals",
    name: "Family Bundle",
    emoji: "👪",
    price: 19.99,
    description: "4 burgers, 4 small fries, and 4 small drinks.",
    tags: ["Deal", "Family", "Bundle"],
    nutrition: {
      calories: "Varies",
      protein: "Varies",
      carbs: "Varies",
      fat: "Varies",
    },
  },

  // Game Day Munchies
  {
    id: "game-day-1",
    category: "game-day",
    name: "Jumbo Jack Munchie Meal",
    emoji: "🏈",
    price: 8.99,
    description: "Jumbo Jack, 2 tacos, curly fries, and a small drink.",
    tags: ["Game Day", "Munchie", "Combo"],
    nutrition: {
      calories: 1200,
      protein: 38,
      carbs: 140,
      fat: 62,
    },
  },
  {
    id: "game-day-2",
    category: "game-day",
    name: "Party Taco Pack",
    emoji: "🎉",
    price: 12.99,
    description: "20 tiny tacos with 3 dipping sauces.",
    tags: ["Game Day", "Party", "Tacos"],
    nutrition: {
      calories: 1100,
      protein: 36,
      carbs: 110,
      fat: 60,
    },
  },
  {
    id: "game-day-3",
    category: "game-day",
    name: "Loaded Curly Fries",
    emoji: "🍟",
    price: 4.99,
    description: "Curly fries topped with cheese sauce, bacon bits, and jalapeños.",
    tags: ["Game Day", "Loaded", "Fries"],
    nutrition: {
      calories: 580,
      protein: 12,
      carbs: 58,
      fat: 34,
    },
  },

  // Munchies Under $4
  {
    id: "munchie-1",
    category: "munchies",
    name: "Jr. Bacon Cheeseburger",
    emoji: "🍔",
    price: 2.49,
    description: "Beef patty with bacon, cheese, lettuce, tomato, and mayo on a bun.",
    tags: ["Value", "Burger", "Bacon"],
    nutrition: {
      calories: 420,
      protein: 20,
      carbs: 32,
      fat: 24,
    },
  },
  {
    id: "munchie-2",
    category: "munchies",
    name: "Value Fries",
    emoji: "🍟",
    price: 1.49,
    description: "Value-sized portion of our crispy, golden french fries.",
    tags: ["Value", "Fries", "Side"],
    nutrition: {
      calories: 230,
      protein: 3,
      carbs: 30,
      fat: 11,
    },
  },
  {
    id: "munchie-3",
    category: "munchies",
    name: "Chicken Nuggets (4pc)",
    emoji: "🍗",
    price: 1.99,
    description: "Four pieces of all-white-meat chicken nuggets with your choice of dipping sauce.",
    tags: ["Value", "Nuggets", "Chicken"],
    nutrition: {
      calories: 190,
      protein: 10,
      carbs: 12,
      fat: 12,
    },
  },
  {
    id: "munchie-4",
    category: "munchies",
    name: "2 Tacos",
    emoji: "🌮",
    price: 1.99,
    description: "Two crunchy tacos with American cheese, shredded lettuce, and taco sauce.",
    tags: ["Value", "Tacos", "Classic"],
    nutrition: {
      calories: 340,
      protein: 12,
      carbs: 30,
      fat: 18,
    },
  },

  // Burger Combos
  {
    id: "burger-combo-1",
    category: "burger-combos",
    name: "Jumbo Jack Combo",
    emoji: "🍔",
    price: 6.99,
    description: "Jumbo Jack with small fries and a small drink.",
    tags: ["Combo", "Burger", "Classic"],
    nutrition: {
      calories: 830,
      protein: 27,
      carbs: 98,
      fat: 43,
    },
  },
  {
    id: "burger-combo-2",
    category: "burger-combos",
    name: "Bacon Ultimate Cheeseburger Combo",
    emoji: "🍔",
    price: 9.99,
    description: "Bacon Ultimate Cheeseburger with small fries and a small drink.",
    tags: ["Combo", "Burger", "Bacon"],
    nutrition: {
      calories: 1250,
      protein: 56,
      carbs: 100,
      fat: 77,
    },
  },
  {
    id: "burger-combo-3",
    category: "burger-combos",
    name: "Sourdough Jack Combo",
    emoji: "🍔",
    price: 8.99,
    description: "Sourdough Jack with small fries and a small drink.",
    tags: ["Combo", "Burger", "Sourdough"],
    nutrition: {
      calories: 1030,
      protein: 38,
      carbs: 94,
      fat: 61,
    },
  },

  // Late Night
  {
    id: "late-night-1",
    category: "late-night",
    name: "Munchie Meal Box",
    emoji: "🌙",
    price: 9.99,
    description: "Your choice of sandwich with two tacos, halfsie fries (half curly, half regular), and a small drink.",
    tags: ["Late Night", "Munchie", "Box"],
    nutrition: {
      calories: 1350,
      protein: 42,
      carbs: 156,
      fat: 72,
    },
  },
  {
    id: "late-night-2",
    category: "late-night",
    name: "Stacked Grilled Cheese Burger",
    emoji: "🧀",
    price: 6.49,
    description: "Beef patty between two grilled cheese sandwiches with lettuce, tomato, and mayo.",
    tags: ["Late Night", "Burger", "Cheese"],
    nutrition: {
      calories: 860,
      protein: 42,
      carbs: 58,
      fat: 54,
    },
  },
  {
    id: "late-night-3",
    category: "late-night",
    name: "Loaded Nuggets",
    emoji: "🍗",
    price: 5.99,
    description: "10 chicken nuggets topped with cheese sauce, bacon bits, and ranch.",
    tags: ["Late Night", "Nuggets", "Loaded"],
    nutrition: {
      calories: 720,
      protein: 34,
      carbs: 42,
      fat: 48,
    },
  },

  // Lighter Options
  {
    id: "lighter-1",
    category: "lighter",
    name: "Grilled Chicken Salad",
    emoji: "🥗",
    price: 6.99,
    description: "Grilled chicken breast on a bed of mixed greens with grape tomatoes, cucumber, and shredded carrots.",
    tags: ["Salad", "Grilled", "Chicken"],
    nutrition: {
      calories: 320,
      protein: 30,
      carbs: 16,
      fat: 16,
    },
  },
  {
    id: "lighter-2",
    category: "lighter",
    name: "Side Salad",
    emoji: "🥗",
    price: 2.49,
    description: "Mixed greens with grape tomatoes, cucumber, and shredded carrots.",
    tags: ["Salad", "Side", "Vegetarian"],
    nutrition: {
      calories: 80,
      protein: 4,
      carbs: 10,
      fat: 4,
    },
  },
  {
    id: "lighter-3",
    category: "lighter",
    name: "Grilled Chicken Sandwich",
    emoji: "🍗",
    price: 5.99,
    description: "Grilled chicken breast with lettuce, tomato, and mayo on a toasted bun.",
    tags: ["Sandwich", "Grilled", "Chicken"],
    nutrition: {
      calories: 420,
      protein: 28,
      carbs: 42,
      fat: 16,
    },
  },

  // Kids
  {
    id: "kids-1",
    category: "kids",
    name: "Kids Chicken Nuggets",
    emoji: "🍗",
    price: 4.49,
    description: "4 chicken nuggets with small fries, choice of drink, and a toy.",
    tags: ["Kids", "Nuggets", "Meal"],
    nutrition: {
      calories: 420,
      protein: 13,
      carbs: 42,
      fat: 23,
    },
  },
  {
    id: "kids-2",
    category: "kids",
    name: "Kids Hamburger",
    emoji: "🍔",
    price: 4.49,
    description: "Hamburger with small fries, choice of drink, and a toy.",
    tags: ["Kids", "Burger", "Meal"],
    nutrition: {
      calories: 450,
      protein: 15,
      carbs: 48,
      fat: 22,
    },
  },
  {
    id: "kids-3",
    category: "kids",
    name: "Kids Grilled Cheese",
    emoji: "🧀",
    price: 4.29,
    description: "Grilled cheese sandwich with small fries, choice of drink, and a toy.",
    tags: ["Kids", "Cheese", "Meal"],
    nutrition: {
      calories: 410,
      protein: 12,
      carbs: 46,
      fat: 20,
    },
  },
]
